Repository atlp-rwanda/atlp-pulse-fn, pull requests merged in 2022-10, with the labels that each got.

#122 #DP-119 Build and publish docker image for production application
  .dockerignore
  .github/workflows/prod_app_deploy.yml
  Dockerfile
Labels: Need Reviews, Top Priority

#127 #DP-119 Build and publish docker image for production application
  .dockerignore
  Dockerfile
Labels: Need Reviews

#124 integrated BE with FE on user registration and user invite
  public/locales/en/translation.json
  public/locales/fr/translation.json
  public/locales/kn/translation.json
  src/App.tsx
  src/Mutations/manageStudentMutations.tsx
  src/components/tests/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  src/containers/Routes.tsx
  src/containers/admin-dashBoard/ManagerRoles.tsx
  src/pages/AdminTraineeDashboard.tsx
  src/pages/Organization/AdminLogin.tsx
  src/pages/Organization/Message.tsx
  src/pages/Organization/Mutations.tsx
  src/pages/Organization/Orglogin.tsx
  src/pages/Organization/UserRegister.tsx
  src/pages/tests/__snapshots__/AdminLogin.test.tsx.snap
  src/pages/tests/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  src/pages/tests/__snapshots__/OrgLogin.test.tsx.snap
  src/tests/__snapshots__/App.test.tsx.snap
  src/utils/PrivateRoute.tsx
Labels: Ready For Merge

#130 #DP-108 Fix URI naming
  src/Routes.tsx
  src/components/Header.tsx
  src/components/Payment-steps/steps/Complete.tsx
  src/components/tests/__snapshots__/Header.test.tsx.snap
  src/containers/Routes.tsx
  src/containers/tests/__snapshots__/MainRoutes.test.tsx.snap
  src/pages/Organization/AdminLogin.tsx
  src/pages/Organization/Orglogin.tsx
  src/pages/Organization/UserRegister.tsx
  src/pages/tests/__snapshots__/AdminLogin.test.tsx.snap
  src/pages/tests/__snapshots__/OrgLogin.test.tsx.snap
  src/tests/__snapshots__/Siderbar.test.tsx.snap
Labels: Need Reviews

#131 #DP-112 Fix role display
  src/components/ProfileDropdown.tsx
  src/components/tests/__snapshots__/ProfileDropdown.test.tsx.snap
  src/utils/PrivateRoute.tsx
Labels: Need Reviews

#135 fix profile issue integration
  .github/workflows/review_app_deploy.yml
  src/App.tsx
  src/Routes.tsx
  src/components/Calendar.tsx
  src/components/ProfileDropdown.tsx
  src/components/ProfileTabs.tsx
  src/containers/Routes.tsx
  src/hook/useAuth.tsx
  src/pages/Organization/Orglogin.tsx
  src/pages/Profile.tsx
  src/pages/ProfileEdit.tsx
  src/pages/tests/__snapshots__/OrgLogin.test.tsx.snap
  src/pages/tests/__snapshots__/Profile.test.tsx.snap
  src/tests/__snapshots__/App.test.tsx.snap
Labels: Ready For Merge

#134 Fix logout and settings
  .github/workflows/review_app_deploy.yml
  src/components/Sidebar.tsx
  src/components/tests/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  src/components/tests/__snapshots__/DashHeader.test.tsx.snap
  src/components/tests/__snapshots__/SideNavLink.test.tsx.snap
  src/pages/tests/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  src/pages/tests/__snapshots__/Admindash.test.tsx.snap
  src/pages/tests/__snapshots__/GradingSystem.test.tsx.snap
  src/pages/tests/__snapshots__/TraineeRatingDashboard.test.tsx.snap
  src/pages/tests/__snapshots__/UpdateTraineeRating.test.tsx.snap
Labels: Need Reviews

#141 DP-120 Signup-enhancement
  .github/workflows/review_app_deploy.yml
  public/locales/fr/translation.json
  public/locales/kn/translation.json
  src/Mutations/manageStudentMutations.tsx
  src/components/ControlledSelect.tsx
  src/containers/Routes.tsx
  src/containers/admin-dashBoard/ManagerRoles.tsx
  src/dummyData/comingSoonPage.json
  src/index.css
  src/pages/AdminTraineeDashboard.tsx
  src/pages/Comingsoon.tsx
  src/pages/Organization/AdminLogin.tsx
  src/pages/Organization/Message.tsx
  src/pages/Organization/Mutations.tsx
  src/pages/Organization/UserRegister.tsx
  src/pages/Pricing.tsx
  src/pages/tests/AdminLogin.test.tsx
  src/pages/tests/__snapshots__/userRegister.test.tsx.snap
Labels: Ready For Merge

#144 fixing issues on manage ratings
  .github/workflows/review_app_deploy.yml
  public/locales/fr/translation.json
  public/locales/kn/translation.json
  src/Mutations/Ratings.tsx
  src/components/Sidebar.tsx
  src/containers/DashRoutes.tsx
  src/pages/AdminRatings.tsx
  src/pages/TraineeRatingDashboard.tsx
  src/pages/UpdatedRatingDashboard.tsx
  src/pages/tests/__snapshots__/UpdateTraineeRating.test.tsx.snap
  src/pages/tests/__snapshots__/userRegister.test.tsx.snap
Labels: Ready For Merge

#136 Fix Coverage
  .github/workflows/main.yml
  jest.config.js
  package-lock.json
  package.json
  src/Routes.tsx
  src/components/Calendar.tsx
  src/components/DashHeader.tsx
  src/components/DataPagination.tsx
  src/components/PricingCard.tsx
  src/components/ProgramIcon.tsx
  src/components/Sidebar.tsx
  src/components/tests/AdminTraineeDashboard.test.tsx
  src/containers/DashRoutes.tsx
  src/containers/Routes.tsx
  src/containers/admin-dashBoard/CreateCohortModal.tsx
  src/containers/admin-dashBoard/CreateProgramModal.tsx
  src/containers/admin-dashBoard/ManagerRoles.tsx
  src/containers/admin-dashBoard/UpdateProgramModal.tsx
  src/containers/tests/DashRoutes.test.tsx
  src/containers/tests/__snapshots__/DashRoutes.test.tsx.snap
  src/hook/useAuth.tsx
  src/pages/AdminTraineeDashboard.tsx
  src/pages/OrgRegister.tsx
  src/pages/Organization/AdminLogin.tsx
  src/pages/Organization/UserRegister.tsx
  src/pages/Profile.tsx
  src/pages/TraineeRatingDashboard.tsx
  src/pages/UpdatedRatingDashboard.tsx
  src/pages/tests/Error.test.tsx
  src/pages/tests/message.test.tsx
  src/tests/ProtectedRoutes.test.tsx
  src/utils/formatDate.tsx
  webpack.config.js
Labels: Need Reviews, Ready For Merge

#152 ft(display):Display trainees in cohort
  .github/workflows/review_app_deploy.yml
  atlp-pulse-fn@2.0.0
  npx
  src/Mutations/manageStudentMutations.tsx
  src/components/ModalDataTable.tsx
  src/containers/admin-dashBoard/CohortTraineeModal.tsx
  src/containers/admin-dashBoard/Cohorts.tsx
  src/containers/admin-dashBoard/tests/__snapshots__/Cohorts.test.tsx.snap
  src/pages/AdminTraineeDashboard.tsx
  src/pages/Organization/Orglogin.tsx
  src/pages/tests/__snapshots__/Admindash.test.tsx.snap
  src/pages/tests/__snapshots__/OrgLogin.test.tsx.snap
  src/pages/tests/__snapshots__/userRegister.test.tsx.snap
Labels: Ready For Merge

#153 fix-profile-image
  .github/workflows/dev_deploy.yml
  .github/workflows/main.yml
  .github/workflows/review_app_deploy.yml
  .husky/pre-commit
  package-lock.json
  package.json
  src/Mutations/User.tsx
  src/components/DashHeader.tsx
  src/components/ProfileCoverpage.tsx
  src/components/ProfileTabs.tsx
  src/components/Spinner.tsx
  src/components/tests/DashHeader.test.tsx
  src/components/tests/ProfileCoverpage.test.tsx
  src/components/tests/ProfileTabs.test.tsx
  src/components/tests/__snapshots__/DashHeader.test.tsx.snap
  src/components/tests/__snapshots__/ProfileCoverpage.test.tsx.snap
  src/hook/useAuth.tsx
  src/pages/Organization/LoginMutation.tsx
  src/pages/Profile.tsx
  src/pages/tests/OrgLogin.test.tsx
  src/pages/tests/OrgRegister.test.tsx
  src/pages/tests/__snapshots__/Profile.test.tsx.snap
Labels: Need Reviews
