Repository atlp-rwanda/atlp-pulse-fn, pull requests merged in 2022-07, with the labels that each got.

#5 #DP-37 chore: Setup tailwind
  package-lock.json
  package.json
  postcss.config.js
  src/index.css
  src/index.tsx
  tailwind.config.js
  webpack.config.js
Labels: Need Reviews

#7 #DP-39 chore: configure linting
  .eslintrc.json
  .gitignore
  .husky/pre-commit
  .prettierignore
  .prettierrc
  package-lock.json
  package.json
  postcss.config.js
  src/index.tsx
  tailwind.config.js
  tsconfig.json
  webpack.config.js
Labels: Ready For Merge

#6 #DP-38 chore: Setup jest
  babelrc
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/App.tsx.html
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov.info
  jest.config.js
  package-lock.json
  package.json
  src/App.tsx
  src/index.tsx
  src/tests/App.test.tsx
  src/tests/__snapshots__/App.test.tsx.snap
Labels: Ready For Merge

#9 #DP-36 ft(design): Landing page
  .DS_Store
  .husky/pre-commit
  custom.d.ts
  index.html
  package-lock.json
  package.json
  src/.DS_Store
  src/App.tsx
  src/Routes.tsx
  src/assets/body.svg
  src/assets/logo.svg
  src/assets/logoWhite.svg
  src/assets/lpageSvg.svg
  src/components/Footer.tsx
  src/components/Header.tsx
  src/hook/useDarkMode.ts
  src/index.css
  src/index.tsx
  src/pages/Home.tsx
  src/pages/OrgRegister.tsx
  tailwind.config.js
  tsconfig.json
  webpack.config.js
Labels: Ready For Merge

#10 #DP-49 ft(orgAuth): Organization login pages
  package-lock.json
  src/Routes.tsx
  src/components/Header.tsx
  src/index.tsx
  src/pages/Home.tsx
  src/pages/Organization/Orggooglelogin.tsx
  src/pages/Organization/Orglogin.tsx
Labels: Ready For Merge

#15 #DP-51 fix: Landing page fixes
  .gitignore
  .husky/pre-commit
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/App.tsx.html
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov.info
  package.json
  src/.DS_Store
  src/App.tsx
  src/assets/landing.svg
  src/components/Footer.tsx
  src/components/Header.tsx
  src/hook/useDarkMode.ts
  src/pages/Home.tsx
  webpack.config.js
Labels: Ready For Merge

#17 #DP-55 chore: CI/CD configuration
  .coveralls.yml
  .github/workflows/dev_deploy.yml
  .github/workflows/main.yml
  .gitignore
  README.md
  jest.config.js
  package-lock.json
  package.json
  src/tests/App.test.tsx
  src/tests/__snapshots__/App.test.tsx.snap
  test/jest/__mocks__/fileMock.js
  test/jest/__mocks__/styleMock.js
Labels: Ready For Merge

#13 #DP-50 (docs): Improve readme file
  .gitignore
  .husky/pre-commit
  README.md
  index.html
  package.json
Labels: documentation, Ready For Merge

#8 #DP-41 feat: pricing components
  .github/pull_request_template.md
  package-lock.json
  package.json
  src/Routes.tsx
  src/components/Header.tsx
  src/components/PricingCard.tsx
  src/components/PricingForm.tsx
  src/index.tsx
  src/pages/Pricing.tsx
  src/pages/PricingForm.tsx
  src/tests/__snapshots__/App.test.tsx.snap
Labels: Ready For Merge

#18 #DP-52 feat: Admin login page
  src/Routes.tsx
  src/containers/Routes.tsx
  src/pages/OrgRegister.tsx
  src/pages/Organization/AdminLogin.tsx
  src/pages/Organization/Orggooglelogin.tsx
  src/pages/Organization/Orglogin.tsx
Labels: Ready For Merge

#19 #DP-56 fix: Register Organisation page fixes
  package-lock.json
  src/components/Header.tsx
  src/pages/OrgRegister.tsx
Labels: Ready For Merge

#25 #DP-47 feat: Settings page
  .eslintrc.json
  package-lock.json
  package.json
  public/locales/en/translation.json
  public/locales/fr/translation.json
  public/locales/kn/translation.json
  server.mjs
  src/components/Card.tsx
  src/components/Chart.tsx
  src/components/PricingCard.tsx
  src/components/Sidebar.tsx
  src/components/tests/__snapshots__/DashHeader.test.tsx.snap
  src/containers/DashRoutes.tsx
  src/containers/Routes.tsx
  src/i18n.js
  src/index.tsx
  src/pages/Organization/AdminLogin.tsx
  src/pages/Pricing.tsx
  src/pages/Settings.tsx
  src/pages/SupAdDashboard.tsx
  src/pages/tests/Settings.test.tsx
  src/pages/tests/__snapshots__/SupAdDashboard.test.tsx.snap
  src/utils/getLanguage.tsx
Labels: Ready For Merge

#33 fix: register organization
  package-lock.json
  package.json
  public/locales/en/translation.json
  public/locales/fr/translation.json
  src/containers/Routes.tsx
  src/pages/OrgRegister.tsx
  src/pages/tests/OrgRegister.test.tsx
  src/pages/tests/__snapshots__/OrgRegister.test.tsx.snap
Labels: Ready For Merge

#38 #DP-72 feat: internationalization
  .eslintrc
  package-lock.json
  package.json
  public/locales/en/translation.json
  public/locales/fr/translation.json
  public/locales/kn/translation.json
  src/components/Chart.tsx
  src/components/DashHeader.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/PricingCard.tsx
  src/components/PricingForm.tsx
  src/components/SearchBar.tsx
  src/components/Sidebar.tsx
  src/containers/DashRoutes.tsx
  src/containers/tests/__snapshots__/MainRoutes.test.tsx.snap
  src/pages/Home.tsx
  src/pages/NotFound.tsx
  src/pages/OrgRegister.tsx
  src/pages/Organization/AdminLogin.tsx
  src/pages/Organization/Orglogin.tsx
  src/pages/Pricing.tsx
  src/pages/Settings.tsx
  src/pages/SupAdDashboard.tsx
  src/pages/tests/__snapshots__/AdminLogin.test.tsx.snap
  src/pages/tests/__snapshots__/NotFound.test.tsx.snap
  src/pages/tests/__snapshots__/OrgLogin.test.tsx.snap
  src/pages/tests/__snapshots__/OrgRegister.test.tsx.snap
  src/pages/tests/__snapshots__/SupAdDashboard.test.tsx.snap
  src/tests/__snapshots__/App.test.tsx.snap
  src/utils/getLanguage.tsx
Labels: Ready For Merge, Top Priority

#28 #DP-9 ft: Admin dashboard
  public/locales/en/translation.json
  public/locales/fr/translation.json
  src/components/Sidebar.tsx
  src/components/tests/__snapshots__/DashHeader.test.tsx.snap
  src/containers/DashRoutes.tsx
  src/containers/admin-dashBoard/Cohorts.tsx
  src/containers/admin-dashBoard/ManagerRoles.tsx
  src/containers/admin-dashBoard/Sessions.tsx
  src/containers/admin-dashBoard/tests/Cohorts.test.tsx
  src/containers/admin-dashBoard/tests/ManageRole.test.tsx
  src/containers/admin-dashBoard/tests/Sessions.test.tsx
  src/containers/tests/__snapshots__/DashRoutes.test.tsx.snap
  src/pages/OrgRegister.tsx
  src/pages/tests/Admindash.test.tsx
  src/pages/tests/__snapshots__/Admindash.test.tsx.snap
  src/pages/tests/__snapshots__/OrgRegister.test.tsx.snap
Labels: Ready For Merge

#26 #DP-7 feat: admin trainee dashboard
  .github/workflows/dev_deploy.yml
  .github/workflows/main.yml
  package-lock.json
  package.json
  public/locales/en/translation.json
  public/locales/fr/translation.json
  public/locales/kn/translation.json
  server.mjs
  src/.DS_Store
  src/App.tsx
  src/components/Sidebar.tsx
  src/components/Siderbar.tsx
  src/components/tests/AdminTraineeDashboard.test.tsx
  src/components/tests/Footer.test.tsx
  src/components/tests/ScrollToTop.test.tsx
  src/components/tests/TraineeRatingDashboard.test.tsx
  src/components/tests/UpdatedRatingDashboard.test.tsx
  src/components/tests/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  src/components/tests/__snapshots__/Footer.test.tsx.snap
  src/components/tests/__snapshots__/ScrollToTop.test.tsx.snap
  src/components/tests/__snapshots__/TraineeRatingDashboard.test.tsx.snap
  src/components/tests/__snapshots__/UpdatedRatingDashboard.test.tsx.snap
  src/containers/DashRoutes.tsx
  src/containers/tests/__snapshots__/MainRoutes.test.tsx.snap
  src/dummyData/developers.json
  src/dummyData/developers2.json
  src/dummyData/developers3.json
  src/pages/AdminTraineeDashboard.tsx
  src/pages/Home.tsx
  src/pages/TraineeRatingDashboard.tsx
  src/pages/UpdatedRatingDashboard.tsx
  src/pages/tests/TraineeRatingDashboard.test.tsx
  src/pages/tests/UpdatedRatingDashboard.test.tsx
  src/pages/tests/__snapshots__/TraineeRatingDashboard.test.tsx.snap
  src/pages/tests/__snapshots__/UpdatedRatingDashboard.test.tsx.snap
  src/tests/Pricing.test.tsx
  src/tests/Siderbar.test.tsx
  src/tests/__snapshots__/App.test.tsx.snap
  src/tests/__snapshots__/Pricing.test.tsx.snap
  src/tests/__snapshots__/Siderbar.test.tsx.snap
  tsconfig.json
Labels: Ready For Merge

#43 #DP-74 fix: Sidebar fixes
  package-lock.json
  public/locales/en/translation.json
  public/locales/fr/translation.json
  public/locales/kn/translation.json
  src/components/Sidebar.tsx
  src/components/Siderbar.tsx
  src/components/tests/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  src/components/tests/__snapshots__/DashHeader.test.tsx.snap
  src/components/tests/__snapshots__/SideNavLink.test.tsx.snap
  src/components/tests/__snapshots__/TraineeRatingDashboard.test.tsx.snap
  src/components/tests/__snapshots__/UpdatedRatingDashboard.test.tsx.snap
  src/containers/DashRoutes.tsx
  src/pages/TraineeDashboard.tsx
  src/pages/tests/__snapshots__/TraineeDashboard.test.tsx.snap
  src/pages/tests/__snapshots__/TraineeRatingDashboard.test.tsx.snap
  src/pages/tests/__snapshots__/UpdatedRatingDashboard.test.tsx.snap
Labels: Ready For Merge, Top Priority

#45 fix: button components
  package.json
  public/locales/en/translation.json
  public/locales/fr/translation.json
  public/locales/kn/translation.json
  src/App.tsx
  src/components/Buttons.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/PricingCard.tsx
  src/components/PricingForm.tsx
  src/components/SideNavLink.tsx
  src/components/TraineeAttendance.tsx
  src/components/TraineeAttendanceDetails.tsx
  src/components/TraineePerformance.tsx
  src/components/TraineePerformanceDetails.tsx
  src/components/tests/TraineeAttendance.test.tsx
  src/components/tests/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  src/components/tests/__snapshots__/Footer.test.tsx.snap
  src/components/tests/__snapshots__/Header.test.tsx.snap
  src/components/tests/__snapshots__/TraineeAttendance.test.tsx.snap
  src/components/tests/__snapshots__/TraineePerformance.test.tsx.snap
  src/components/tests/__snapshots__/TraineePerformanceDetails.test.tsx.snap
  src/components/tests/__snapshots__/TraineeRatingDashboard.test.tsx.snap
  src/components/tests/__snapshots__/UpdatedRatingDashboard.test.tsx.snap
  src/containers/DashRoutes.tsx
  src/containers/admin-dashBoard/Cohorts.tsx
  src/containers/admin-dashBoard/ManagerRoles.tsx
  src/containers/admin-dashBoard/Sessions.tsx
  src/containers/admin-dashBoard/tests/Sessions.test.tsx
  src/containers/tests/__snapshots__/MainRoutes.test.tsx.snap
  src/dummyData/developers.json
  src/dummyData/developers2.json
  src/dummyData/developers3.json
  src/index.css
  src/pages/AdminTraineeDashboard.tsx
  src/pages/Home.tsx
  src/pages/NotFound.tsx
  src/pages/NotFoundDashboard.tsx
  src/pages/OrgRegister.tsx
  src/pages/Organization/AdminLogin.tsx
  src/pages/Organization/Orglogin.tsx
  src/pages/TraineeRatingDashboard.tsx
  src/pages/UpdatedRatingDashboard.tsx
  src/pages/tests/Admindash.test.tsx
  src/pages/tests/__snapshots__/AdminLogin.test.tsx.snap
  src/pages/tests/__snapshots__/Admindash.test.tsx.snap
  src/pages/tests/__snapshots__/NotFound.test.tsx.snap
  src/pages/tests/__snapshots__/OrgLogin.test.tsx.snap
  src/pages/tests/__snapshots__/OrgRegister.test.tsx.snap
  src/pages/tests/__snapshots__/Pricing.test.tsx.snap
  src/pages/tests/__snapshots__/TraineeRatingDashboard.test.tsx.snap
  src/pages/tests/__snapshots__/UpdatedRatingDashboard.test.tsx.snap
  src/tests/__snapshots__/App.test.tsx.snap
  src/tests/__snapshots__/Pricing.test.tsx.snap
  src/tests/__snapshots__/Siderbar.test.tsx.snap
  src/utils/CheckRoles.tsx
  src/utils/getLanguage.tsx
  tsconfig.json
Labels: Ready For Merge, Top Priority

#27 DP-45 feat: Calendar component
  package-lock.json
  package.json
  public/locales/en/translation.json
  public/locales/fr/translation.json
  public/locales/kn/translation.json
  src/components/Calendar.tsx
  src/components/tests/Calendar.test.tsx
  src/components/tests/__snapshots__/UpdatedRatingDashboard.test.tsx.snap
  src/containers/DashRoutes.tsx
  src/containers/Routes.tsx
  src/pages/Home.tsx
  src/pages/OrgRegister.tsx
  src/pages/UpdatedRatingDashboard.tsx
  src/pages/tests/UpdatedRatingDashboard.test.tsx
  src/pages/tests/__snapshots__/UpdatedRatingDashboard.test.tsx.snap
Labels: Ready For Merge, Top Priority

#40 Ft notification
  .github/workflows/review_app_deploy.yml
  package-lock.json
  package.json
  public/locales/en/translation.json
  public/locales/fr/translation.json
  public/locales/kn/translation.json
  src/components/DashHeader.tsx
  src/components/Notification.tsx
  src/components/tests/__snapshots__/DashHeader.test.tsx.snap
  src/dummyData/notificationDummy.tsx
  src/tests/Notification.test.tsx
  tailwind.config.js
Labels: Ready For Merge, Top Priority
