Repository atlp-rwanda/atlp-pulse-fn, pull requests merged in 2022-09, with the labels that each got.

#79 Fix: Skeleton UI glitch
  .eslintrc
  .husky/pre-commit
  package.json
  src/Skeletons/Square.tsx
  src/Skeletons/tests/Square.test.tsx
  src/Skeletons/tests/__snapshots__/Square.test.tsx.snap
  src/components/DashHeader.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/ProfileCoverpage.tsx
  src/components/ProfileTabs.tsx
  src/components/Skeleton.tsx
  src/components/tests/__snapshots__/Footer.test.tsx.snap
  src/components/tests/__snapshots__/Skeleton.test.tsx.snap
  src/containers/DashRoutes.tsx
  src/containers/tests/__snapshots__/MainRoutes.test.tsx.snap
  src/hook/useAuth.tsx
  src/pages/Home.tsx
  src/pages/Noredirect.tsx
  src/pages/OrgRegister.tsx
  src/pages/Organization/Orglogin.tsx
  src/tests/__snapshots__/App.test.tsx.snap
  src/tests/__snapshots__/Siderbar.test.tsx.snap
  src/utils/CheckRoles.tsx
  src/utils/PrivateRoute.tsx
Labels: Ready For Merge, Top Priority

#80 #DP-104:Feat Protect login
  package-lock.json
  src/ProtectedRoute.tsx
  src/Routes.tsx
  src/components/Notify.tsx
  src/containers/Routes.tsx
  src/tests/Notify.test.tsx
  src/tests/ProtectedRoutes.test.tsx
Labels: Ready For Merge

#75 #DP-75 fix: Pagination
  package-lock.json
  package.json
  public/locales/en/translation.json
  src/ProtectedRoute.tsx
  src/Routes.tsx
  src/Skeletons/Square.tsx
  src/components/DashHeader.tsx
  src/components/DataPagination.tsx
  src/components/DataTable.tsx
  src/components/Pagination.tsx
  src/components/ProfileDropdown.tsx
  src/components/TraineeAttendance.tsx
  src/components/TraineePerformance.tsx
  src/components/tests/TraineeAttendance.test.tsx
  src/components/tests/TraineePerformance.test.tsx
  src/components/tests/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  src/components/tests/__snapshots__/TraineeAttendance.test.tsx.snap
  src/components/tests/__snapshots__/TraineePerformance.test.tsx.snap
  src/components/tests/__snapshots__/TraineeRatingDashboard.test.tsx.snap
  src/components/tests/__snapshots__/UpdatedRatingDashboard.test.tsx.snap
  src/containers/DashRoutes.tsx
  src/containers/Routes.tsx
  src/containers/Trainee/AttendanceDetails.tsx
  src/containers/Trainee/PerformanceDetails.tsx
  src/containers/admin-dashBoard/Cohorts.tsx
  src/containers/admin-dashBoard/ManagerRoles.tsx
  src/containers/admin-dashBoard/Sessions.tsx
  src/containers/admin-dashBoard/tests/Cohorts.test.tsx
  src/containers/admin-dashBoard/tests/ManageRole.test.tsx
  src/containers/admin-dashBoard/tests/Sessions.test.tsx
  src/containers/admin-dashBoard/tests/__snapshots__/ManageRole.test.tsx.snap
  src/dummyData/attendance.json
  src/dummyData/cohort.json
  src/dummyData/performance.json
  src/dummyData/session.json
  src/index.css
  src/pages/AdminTraineeDashboard.tsx
  src/pages/Settings.tsx
  src/pages/TraineeRatingDashboard.tsx
  src/pages/UpdatedRatingDashboard.tsx
  src/pages/tests/AdminTraineeDashboard.test.tsx
  src/pages/tests/Settings.test.tsx
  src/pages/tests/TraineeRatingDashboard.test.tsx
  src/pages/tests/UpdatedRatingDashboard.test.tsx
  src/pages/tests/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  src/pages/tests/__snapshots__/Admindash.test.tsx.snap
  src/pages/tests/__snapshots__/TraineeRatingDashboard.test.tsx.snap
  src/pages/tests/__snapshots__/UpdatedRatingDashboard.test.tsx.snap
Labels: Need Reviews, Ready For Merge

#85 #DP-105 Integration: Manage roles and permissions
  .env.example
  package-lock.json
  package.json
  public/locales/en/translation.json
  public/locales/fr/translation.json
  public/locales/kn/translation.json
  src/Routes.tsx
  src/components/DataPagination.tsx
  src/components/DataTable.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Notify.tsx
  src/components/Pagination.tsx
  src/components/ProfileCoverpage.tsx
  src/components/ProfileTabs.tsx
  src/components/tests/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  src/components/tests/__snapshots__/TraineeRatingDashboard.test.tsx.snap
  src/components/tests/__snapshots__/UpdatedRatingDashboard.test.tsx.snap
  src/containers/admin-dashBoard/AssignRolesMutation.tsx
  src/containers/admin-dashBoard/GetRolesQuery.tsx
  src/containers/admin-dashBoard/ManagerRoles.tsx
  src/containers/admin-dashBoard/RoleMutation.tsx
  src/containers/admin-dashBoard/UserMutation.tsx
  src/containers/admin-dashBoard/createRoleMutation.tsx
  src/containers/admin-dashBoard/tests/ManageRole.test.tsx
  src/containers/admin-dashBoard/tests/Sessions.test.tsx
  src/containers/admin-dashBoard/tests/__snapshots__/ManageRole.test.tsx.snap
  src/dummyData/roles.json
  src/hook/useAuth.tsx
  src/index.tsx
  src/pages/Home.tsx
  src/pages/Noredirect.tsx
  src/pages/OrgRegister.tsx
  src/pages/Organization/Orglogin.tsx
  src/pages/tests/AdminLogin.test.tsx
  src/pages/tests/Admindash.test.tsx
  src/pages/tests/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  src/pages/tests/__snapshots__/Admindash.test.tsx.snap
  src/pages/tests/__snapshots__/Settings.test.tsx.snap
  src/pages/tests/__snapshots__/TraineeRatingDashboard.test.tsx.snap
  src/pages/tests/__snapshots__/UpdatedRatingDashboard.test.tsx.snap
  src/utils/CheckRoles.tsx
  webpack.config.js
Labels: Ready For Merge

#82 #DP-103 feat: Profile settings integration
  .env.example
  .eslintrc
  .github/workflows/dev_deploy.yml
  .github/workflows/main.yml
  .husky/pre-commit
  package-lock.json
  package.json
  src/Mutations/User.tsx
  src/Routes.tsx
  src/Skeletons/OnError.tsx
  src/components/CountrySelector.tsx
  src/components/DataPagination.tsx
  src/components/DataTable.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Input.tsx
  src/components/Notify.tsx
  src/components/Pagination.tsx
  src/components/ProfileCoverpage.tsx
  src/components/ProfileTabs.tsx
  src/components/tests/ProfileTabs.test.tsx
  src/components/tests/__snapshots__/Header.test.tsx.snap
  src/constants/formFields.ts
  src/containers/tests/__snapshots__/MainRoutes.test.tsx.snap
  src/hook/useAuth.tsx
  src/index.tsx
  src/pages/Home.tsx
  src/pages/Noredirect.tsx
  src/pages/OrgRegister.tsx
  src/pages/Organization/AdminLogin.tsx
  src/pages/Organization/LoginMutation.tsx
  src/pages/Organization/Orglogin.tsx
  src/pages/Profile.tsx
  src/pages/ProfileEdit.tsx
  src/pages/tests/AdminLogin.test.tsx
  src/pages/tests/Profile.test.tsx
  src/pages/tests/Settings.test.tsx
  src/pages/tests/__snapshots__/Profile.test.tsx.snap
  src/pages/tests/__snapshots__/Settings.test.tsx.snap
  src/tests/__snapshots__/Siderbar.test.tsx.snap
  src/utils/CheckRoles.tsx
Labels: Need Reviews

#101 #DP-91 feat(fix): role management
  package-lock.json
  package.json
  src/components/DataTable.tsx
  src/containers/admin-dashBoard/ManagerRoles.tsx
Labels: Need Reviews

#112 Bug(fix): Fix CI deployment
  .github/workflows/dev_deploy.yml
  .github/workflows/main.yml
  .github/workflows/review_app_deploy.yml
  src/Routes.tsx
  src/pages/tests/AdminLogin.test.tsx
Labels: Ready For Merge, Top Priority
