Repository atlp-rwanda/atlp-pulse-fn, pull requests merged in 2022-08, with the labels that each got.

#47 Fix trainee dashboard
  package-lock.json
  public/locales/en/translation.json
  public/locales/fr/translation.json
  public/locales/kn/translation.json
  src/components/Sidebar.tsx
  src/components/Siderbar.tsx
  src/components/TraineeAttendance.tsx
  src/components/TraineeAttendanceDetails.tsx
  src/components/TraineeComments.tsx
  src/components/TraineePerformance.tsx
  src/components/TraineePerformanceDetails.tsx
  src/components/tests/TraineeAttendanceDetails.tsx
  src/components/tests/TraineeComments.tsx
  src/components/tests/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  src/components/tests/__snapshots__/DashHeader.test.tsx.snap
  src/components/tests/__snapshots__/SideNavLink.test.tsx.snap
  src/components/tests/__snapshots__/TraineeAttendance.test.tsx.snap
  src/components/tests/__snapshots__/TraineePerformance.test.tsx.snap
  src/components/tests/__snapshots__/TraineePerformanceDetails.test.tsx.snap
  src/components/tests/__snapshots__/TraineeRatingDashboard.test.tsx.snap
  src/components/tests/__snapshots__/UpdatedRatingDashboard.test.tsx.snap
  src/containers/Trainee/AttendanceDetails.tsx
  src/containers/Trainee/PerformanceDetails.tsx
  src/containers/Trainee/tests/AttendanceDetails.test.tsx
  src/containers/Trainee/tests/PerformanceDetails.test.tsx
  src/containers/Trainee/tests/__snapshots__/AttendanceDetails.test.tsx.snap
  src/containers/Trainee/tests/__snapshots__/PerformanceDetails.test.tsx.snap
  src/containers/admin-dashBoard/Cohorts.tsx
  src/containers/admin-dashBoard/ManagerRoles.tsx
  src/pages/AdminDashboard.tsx
  src/pages/AdminTraineeDashboard.tsx
  src/pages/Organization/AdminLogin.tsx
  src/pages/Settings.tsx
  src/pages/TraineeRatingDashboard.tsx
  src/pages/UpdatedRatingDashboard.tsx
  src/pages/tests/__snapshots__/AdminLogin.test.tsx.snap
  src/pages/tests/__snapshots__/Admindash.test.tsx.snap
  src/pages/tests/__snapshots__/Settings.test.tsx.snap
  src/pages/tests/__snapshots__/TraineeRatingDashboard.test.tsx.snap
  src/pages/tests/__snapshots__/UpdatedRatingDashboard.test.tsx.snap
Labels: Ready For Merge

#51 #DP-89: (Feat) Homepage translation
  src/components/Footer.tsx
  src/components/tests/__snapshots__/Footer.test.tsx.snap
  src/containers/tests/__snapshots__/MainRoutes.test.tsx.snap
  src/tests/__snapshots__/App.test.tsx.snap
  src/tests/__snapshots__/Siderbar.test.tsx.snap
Labels: Ready For Merge

#56 #DP-92 fix(design): comment page
  public/locales/en/translation.json
  public/locales/fr/translation.json
  public/locales/kn/translation.json
  src/components/CommentCard.tsx
  src/components/TraineeComments.tsx
  src/components/TraineePerformanceDetails.tsx
  src/components/tests/__snapshots__/TraineePerformanceDetails.test.tsx.snap
  src/containers/Trainee/AttendanceDetails.tsx
  src/containers/Trainee/PerformanceDetails.tsx
  src/containers/Trainee/tests/__snapshots__/AttendanceDetails.test.tsx.snap
  src/containers/Trainee/tests/__snapshots__/PerformanceDetails.test.tsx.snap
  src/dummyData/comments.json
Labels: Ready For Merge

#55 #DP-46 ft: Grading system
  public/locales/en/translation.json
  public/locales/fr/translation.json
  public/locales/kn/translation.json
  src/components/Sidebar.tsx
  src/components/TraineeComments.tsx
  src/containers/DashRoutes.tsx
  src/dummyData/gradingSystem.json
  src/pages/GradingSystem.tsx
  src/pages/tests/GradingSystem.test.tsx
  src/pages/tests/__snapshots__/GradingSystem.test.tsx.snap
Labels: Ready For Merge

#50 #DP-60 Ft: Profile Page
  .DS_Store
  package-lock.json
  package.json
  public/locales/en/translation.json
  public/locales/fr/translation.json
  public/locales/kn/translation.json
  src/components/CountrySelector.tsx
  src/components/Footer.tsx
  src/components/Input.tsx
  src/components/ProfileCoverpage.tsx
  src/components/ProfileTabs.tsx
  src/components/tests/ProfileTabs.test.tsx
  src/components/tests/TraineeAttendanceDetails.tsx
  src/components/tests/TraineeComments.tsx
  src/components/tests/__snapshots__/Footer.test.tsx.snap
  src/constants/countries.ts
  src/constants/formFields.ts
  src/containers/DashRoutes.tsx
  src/containers/Trainee/AttendanceDetails.tsx
  src/containers/Trainee/PerformanceDetails.tsx
  src/containers/Trainee/tests/PerformanceDetails.test.tsx
  src/containers/admin-dashBoard/Cohorts.tsx
  src/containers/tests/__snapshots__/MainRoutes.test.tsx.snap
  src/pages/Home.tsx
  src/pages/OrgRegister.tsx
  src/pages/Profile.tsx
  src/pages/ProfileEdit.tsx
  src/pages/Settings.tsx
  src/pages/tests/Profile.test.tsx
  src/pages/tests/__snapshots__/Profile.test.tsx.snap
  src/pages/tests/__snapshots__/Settings.test.tsx.snap
  src/tests/__snapshots__/App.test.tsx.snap
  src/tests/__snapshots__/Siderbar.test.tsx.snap
Labels: Ready For Merge

#58 DP-78 Fix error/404 page
  public/locales/en/translation.json
  public/locales/fr/translation.json
  public/locales/kn/translation.json
  src/Routes.tsx
  src/assets/NotFoundImg.svg
  src/assets/bg-error-img.jpg
  src/components/Calendar.tsx
  src/components/CommentCard.tsx
  src/components/Header.tsx
  src/components/PricingForm.tsx
  src/components/TraineeAttendance.tsx
  src/components/TraineeAttendanceDetails.tsx
  src/components/TraineeComments.tsx
  src/components/TraineePerformance.tsx
  src/components/TraineePerformanceDetails.tsx
  src/containers/DashRoutes.tsx
  src/containers/Routes.tsx
  src/dummyData/comments.json
  src/dummyData/gradingSystem.json
  src/index.css
  src/pages/Error.tsx
  src/pages/GradingSystem.tsx
  src/pages/Home.tsx
  src/pages/NotFound.tsx
  src/pages/NotFoundDashboard.tsx
  src/pages/OrgRegister.tsx
  src/pages/Organization/Orglogin.tsx
  src/pages/UpdatedRatingDashboard.tsx
  src/pages/tests/Error.test.tsx
  src/pages/tests/GradingSystem.test.tsx
  src/pages/tests/__snapshots__/Error.test.tsx.snap
  src/pages/tests/__snapshots__/NotFound.test.tsx.snap
Labels: Ready For Merge

#61 Feat: Logout dropdown
  public/locales/fr/translation.json
  public/locales/kn/translation.json
  src/components/DashHeader.tsx
  src/components/ProfileDropdown.tsx
  src/components/tests/ProfileDropdown.test.tsx
  src/components/tests/__snapshots__/DashHeader.test.tsx.snap
  src/components/tests/__snapshots__/ProfileDropdown.test.tsx.snap
Labels: Ready For Merge

#65 #DP-95 (Fix): Load time for review apps
  .github/workflows/review_app_deploy.yml
  src/App.tsx
  src/Skeletons/Square.tsx
  src/components/Calendar.tsx
  src/containers/DashRoutes.tsx
  src/containers/Routes.tsx
  src/tests/__snapshots__/App.test.tsx.snap
Labels: Need Reviews

#66 #DP-96 Fix: Unnecessarily message to a restricted page
  src/pages/Organization/AdminLogin.tsx
Labels: Need Reviews

#59 fix: Menu close on mobile
  package.json
  src/components/DashHeader.tsx
  src/components/SideNavLink.tsx
  src/components/Sidebar.tsx
  src/components/TraineeAttendance.tsx
  src/components/tests/SideNavLink.test.tsx
  src/components/tests/TraineeAttendanceDetails.test.tsx
  src/components/tests/TraineeComments.test.tsx
  src/components/tests/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  src/components/tests/__snapshots__/TraineeAttendanceDetails.test.tsx.snap
  src/components/tests/__snapshots__/TraineeComments.test.tsx.snap
  src/components/tests/__snapshots__/TraineeRatingDashboard.test.tsx.snap
  src/components/tests/__snapshots__/UpdatedRatingDashboard.test.tsx.snap
  src/containers/DashRoutes.tsx
  src/containers/Routes.tsx
  src/pages/AdminTraineeDashboard.tsx
  src/pages/GradingSystem.tsx
  src/pages/Home.tsx
  src/pages/TraineeRatingDashboard.tsx
  src/pages/UpdatedRatingDashboard.tsx
  src/pages/tests/__snapshots__/GradingSystem.test.tsx.snap
  src/pages/tests/__snapshots__/TraineeRatingDashboard.test.tsx.snap
  src/pages/tests/__snapshots__/UpdatedRatingDashboard.test.tsx.snap
Labels: Ready For Merge

#54 Fix-role-management-dp-91
  src/components/Pagination.tsx
  src/containers/admin-dashBoard/ManagerRoles.tsx
  src/containers/admin-dashBoard/tests/ManageRole.test.tsx
  src/containers/admin-dashBoard/tests/__snapshots__/ManageRole.test.tsx.snap
  src/dummyData/rolemanagement.json
  src/pages/tests/__snapshots__/Admindash.test.tsx.snap
Labels: Ready For Merge

#64 #DP-94 Fix: Dynamic titles
  public/locales/fr/translation.json
  public/locales/kn/translation.json
  src/components/Calendar.tsx
  src/components/TraineeAttendance.tsx
  src/containers/Trainee/AttendanceDetails.tsx
  src/containers/Trainee/PerformanceDetails.tsx
  src/containers/admin-dashBoard/Cohorts.tsx
  src/containers/admin-dashBoard/ManagerRoles.tsx
  src/containers/admin-dashBoard/Sessions.tsx
  src/hook/useDocumentTitle.tsx
  src/pages/AdminDashboard.tsx
  src/pages/AdminTraineeDashboard.tsx
  src/pages/Error.tsx
  src/pages/GradingSystem.tsx
  src/pages/Home.tsx
  src/pages/OrgRegister.tsx
  src/pages/Organization/AdminLogin.tsx
  src/pages/Organization/Orglogin.tsx
  src/pages/Pricing.tsx
  src/pages/Profile.tsx
  src/pages/ProfileEdit.tsx
  src/pages/Settings.tsx
  src/pages/SupAdDashboard.tsx
  src/pages/TraineeRatingDashboard.tsx
  src/pages/UpdatedRatingDashboard.tsx
Labels: Need Reviews

#73 DP-100 Fix: Settings toggle in light mode
  src/pages/Settings.tsx
  src/pages/tests/Settings.test.tsx
  src/pages/tests/__snapshots__/Settings.test.tsx.snap
Labels: Ready For Merge

#71 DP-99 Fix: profile options
  public/locales/fr/translation.json
  public/locales/kn/translation.json
  src/components/ProfileDropdown.tsx
  src/components/tests/__snapshots__/ProfileDropdown.test.tsx.snap
Labels: Ready For Merge

#77 #DP-102: (Feat) Integration setup
  public/locales/en/translation.json
  public/locales/fr/translation.json
  public/locales/kn/translation.json
  src/components/ButtonLoading.tsx
  src/components/Calendar.tsx
  src/components/Payment-steps/steps/Account.tsx
  src/components/Payment-steps/steps/Complete.tsx
  src/components/Payment-steps/steps/Details.tsx
  src/components/Payment.tsx
  src/components/ProfileDropdown.tsx
  src/components/TraineeAttendance.tsx
  src/components/tests/ButtonLoading.test.tsx
  src/components/tests/__snapshots__/ButtonLoading.test.tsx.snap
  src/components/tests/__snapshots__/ProfileDropdown.test.tsx.snap
  src/containers/Routes.tsx
  src/containers/Trainee/AttendanceDetails.tsx
  src/containers/Trainee/PerformanceDetails.tsx
  src/containers/admin-dashBoard/Cohorts.tsx
  src/containers/admin-dashBoard/ManagerRoles.tsx
  src/containers/admin-dashBoard/Sessions.tsx
  src/dummyData/rolemanagement.json
  src/hook/useAuth.tsx
  src/i18n.ts
  src/index.css
  src/index.tsx
  src/pages/AdminTraineeDashboard.tsx
  src/pages/GradingSystem.tsx
  src/pages/Home.tsx
  src/pages/OrgRegister.tsx
  src/pages/Organization/AdminLogin.tsx
  src/pages/Organization/LoginMutation.tsx
  src/pages/Organization/Orglogin.tsx
  src/pages/ProfileEdit.tsx
  src/pages/TraineeRatingDashboard.tsx
  src/pages/UpdatedRatingDashboard.tsx
  src/pages/tests/AdminLogin.test.tsx
  src/pages/tests/__snapshots__/AdminLogin.test.tsx.snap
  src/tests/Details.test.tsx
Labels: Ready For Merge, Top Priority
