Repository atlp-rwanda/atlp-pulse-fn, pull requests merged in 2023-08, with the labels that each got.

#241 CRUD on grading system
  .gitignore
  src/Mutations/manageStudentMutations.tsx
  src/components/DataTable.tsx
  src/components/Notification.tsx
  src/components/ProfileDropdown.tsx
  src/components/TraineePerformance.tsx
  src/components/loaders/loader1/index.tsx
  src/components/loaders/loader1/style.module.css
  src/components/loaders/loader2/index.tsx
  src/components/loaders/loader2/style.module.css
  src/containers/admin-dashBoard/DeleteGradingsModal.tsx
  src/containers/admin-dashBoard/MakeDefaultModal.tsx
  src/hook/useDarkMode.ts
  src/index.tsx
  src/pages/AdminTraineeDashboard.tsx
  src/pages/GradingSystem.tsx
  src/pages/GradingSystemQuery.ts
  src/pages/gradeSystem/addNew.tsx
  src/pages/gradeSystem/gradeItem.tsx
  src/pages/gradeSystem/style.module.css
  src/pages/ratings/addRatings.tsx
  src/pages/ratings/frame.tsx
  src/pages/ratings/textarea/autosize.tsx
  src/pages/ratings/textarea/index.tsx
  src/pages/tests/GradingSystem.test.tsx
  src/pages/tests/__snapshots__/GradingSystem.test.tsx.snap
Labels: Ready For Merge

#236 fixing sign up for the user
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/containers/admin-dashBoard/tests/Cohorts.test.tsx
  src/pages/AdminDashboard.tsx
  src/pages/Organization/UserRegister.tsx
  src/pages/Profile.tsx
  src/pages/ratings/frame.tsx
  src/pages/tests/__snapshots__/userRegister.test.tsx.snap
  src/pages/tests/userRegister.test.tsx
  target/npmlist.json
  webpack.config.js
Labels: Need Reviews

#251 feat(orgName case insensitive): org name login (#225)
  .gitignore
  src/pages/OrgRegister.tsx
  src/pages/Organization/AdminLogin.tsx
  src/pages/Organization/Orglogin.tsx
  src/pages/Organization/orgName.css
Labels: Ready for review

#250 feature:redesigned help page
  package-lock.json
  src/components/Notification.tsx
  src/hook/ticketsContext.tsx
  src/pages/AllTickets.tsx
  src/pages/HelpPage.tsx
  src/pages/Ticket.tsx
  src/pages/Tickets.tsx
  src/utils/timePassedFormating.ts
Labels: Need Reviews

#263 fix:homepage view
  src/components/Navbar.tsx
  src/index.css
Labels: Need Reviews

#247 Ft(export ratings)
  src/components/Sidebar.tsx
  src/components/tests/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  src/components/tests/__snapshots__/DashHeader.test.tsx.snap
  src/components/tests/__snapshots__/Header.test.tsx.snap
  src/components/tests/__snapshots__/ProfileDropdown.test.tsx.snap
  src/components/tests/__snapshots__/SideNavLink.test.tsx.snap
  src/containers/tests/__snapshots__/MainRoutes.test.tsx.snap
  src/pages/AdminRatings.tsx
  src/pages/TraineeRatingDashboard.tsx
  src/pages/tests/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  src/pages/tests/__snapshots__/Admindash.test.tsx.snap
  src/pages/tests/__snapshots__/Error.test.tsx.snap
  src/pages/tests/__snapshots__/GradingSystem.test.tsx.snap
  src/pages/tests/__snapshots__/OrgLogin.test.tsx.snap
  src/pages/tests/__snapshots__/Pricing.test.tsx.snap
  src/pages/tests/__snapshots__/TraineeRatingDashboard.test.tsx.snap
  src/pages/tests/__snapshots__/UpdateTraineeRating.test.tsx.snap
  src/pages/tests/__snapshots__/userRegister.test.tsx.snap
  src/tests/__snapshots__/App.test.tsx.snap
  src/tests/__snapshots__/Pricing.test.tsx.snap
  src/tests/__snapshots__/Siderbar.test.tsx.snap
  src/tests/__snapshots__/about.test.tsx.snap
  src/utils/PrivateRoute.tsx
Labels: Ready For Merge

#230 Feature/notifications preference
  src/Mutations/notificationMutation.tsx
  src/components/HomePageCard.tsx
  src/components/HomePageCardContainer.tsx
  src/pages/Home.tsx
  src/pages/Settings.tsx
  src/pages/tests/Settings.test.tsx
  src/pages/tests/__snapshots__/Settings.test.tsx.snap
  src/pages/tests/__snapshots__/userRegister.test.tsx.snap
  tailwind.config.js
Labels: Ready for review

#259 Dark theme implementation
  package-lock.json
  src/components/DataTable.tsx
  src/components/Docs/OthersDocs.tsx
  src/components/Docs/TraineeDocs.tsx
  src/components/Header.tsx
  src/components/ModalDataTable.tsx
  src/components/Organizations.tsx
  src/components/TraineePerformance.tsx
  src/components/TraineePerformanceDetails.tsx
  src/components/tests/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  src/components/tests/__snapshots__/TraineeAttendanceDetails.test.tsx.snap
  src/index.css
  src/pages/About.tsx
  src/pages/GradingSystem.tsx
  src/pages/Organization/Orglogin.tsx
  src/pages/Settings.tsx
Labels: Need Reviews

#233 feat:implememtation attendance
  index.html
  package-lock.json
  package.json
  src/Mutations/Attendance.tsx
  src/components/AttendanceStatistics.tsx
  src/components/Docs/TraineeDocs.tsx
  src/components/Sidebar.tsx
  src/components/TraineeAttendance.tsx
  src/containers/DashRoutes.tsx
  src/containers/admin-dashBoard/tests/Attendance.tsx
  src/dummyData/traineeAttendance.ts
  src/index.css
  src/pages/AdminDashboard.tsx
  src/pages/TraineeAttendance.tsx
  src/pages/UpdatedRatingDashboard.tsx
  src/pages/tests/TraineeAttendance.test.tsx
  src/pages/tests/__snapshots__/TraineeAttendance.test.tsx.snap
  tailwind.config.js
  tsconfig.json
Labels: Need Reviews

#269 fix attendance page
  src/components/TraineeAttendance.tsx
  src/containers/DashRoutes.tsx
  src/containers/Trainee/AttendanceDetails.tsx
  src/pages/AdminTraineeDashboard.tsx
  src/pages/Attendance.tsx
  src/pages/TraineeAttendance.tsx
Labels: Ready For Merge

#256 Login and signup new theme
  package-lock.json
  public/locales/en/translation.json
  public/locales/fr/translation.json
  public/locales/kn/translation.json
  src/assets/Functionality_Tree.svg
  src/assets/Property 1=Logo_flie (1).svg
  src/assets/Property 1=Logo_flie-without_message.svg
  src/index.css
  src/pages/OrgRegister.tsx
  src/pages/Organization/AdminLogin.tsx
  src/pages/Organization/Orglogin.tsx
  src/pages/Organization/orgName.css
Labels: Ready For Merge
