Repository atlp-rwanda/atlp-pulse-fn, pull requests merged in 2023-10, with the labels that each got.

#299 #65 Enhance UI/UX on the super admin dashboard
  package-lock.json
  package.json
  src/components/CreateOrganizationModal.tsx
  src/components/Organizations.tsx
Labels: Need Reviews

#298 fixing coudinary
  package-lock.json
  package.json
  src/components/CustomSpinner.tsx
  src/components/ProfileCoverpage.tsx
  src/components/Resume.tsx
  src/components/tests/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  src/components/tests/__snapshots__/ButtonLoading.test.tsx.snap
  src/components/tests/__snapshots__/DashHeader.test.tsx.snap
  src/components/tests/__snapshots__/Footer.test.tsx.snap
  src/components/tests/__snapshots__/Header.test.tsx.snap
  src/containers/admin-dashBoard/Programs.tsx
  src/containers/admin-dashBoard/tests/__snapshots__/Cohorts.test.tsx.snap
  src/containers/tests/__snapshots__/MainRoutes.test.tsx.snap
  src/pages/OrgRegister.tsx
  src/pages/Organization/AdminLogin.tsx
  src/pages/tests/__snapshots__/AdminLogin.test.tsx.snap
  src/pages/tests/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  src/pages/tests/__snapshots__/Admindash.test.tsx.snap
  src/pages/tests/__snapshots__/OrgLogin.test.tsx.snap
  src/pages/tests/__snapshots__/TraineeAttendance.test.tsx.snap
  src/pages/tests/__snapshots__/message.test.tsx.snap
  src/pages/tests/__snapshots__/userRegister.test.tsx.snap
  src/tests/__snapshots__/App.test.tsx.snap
  src/tests/__snapshots__/Siderbar.test.tsx.snap
  src/tests/__snapshots__/about.test.tsx.snap
Labels: Need Reviews

#310 fix: translate error message
  public/locales/en/translation.json
  public/locales/fr/translation.json
  public/locales/kn/translation.json
  src/pages/Organization/AdminLogin.tsx
Labels: Ready for review

#301 FIX(bug): A bug that causes the profile image to stay static.
  package-lock.json
  src/components/ModalDataTable.tsx
  src/components/ratings/ViewWeeklyRatings.tsx
  src/pages/AdminTraineeDashboard.tsx
Labels: Ready For Merge

#312 fix-trainee-dashboard
  src/components/TraineeDashboardChart.tsx
  src/components/ViewComment.tsx
  src/pages/TraineeDashboard.tsx
Labels: Ready For Merge

#318 fix: Replace buttons with icons on organizations page
  src/components/Organizations.tsx
Labels: Ready For Merge

#317 Retrieving coordinators from data
  package-lock.json
  src/containers/admin-dashBoard/CoordinatorModal.tsx
Labels: Ready For Merge

#281 Feat(drop trainee): Admin/coordinator to drop trainee
  package.json
  src/Mutations/manageStudentMutations.tsx
  src/components/ratings/AddNewRatings.tsx
  src/components/ratings/ViewWeeklyRatings.tsx
  src/components/ratings/hooks/useAddNewRating.tsx
  src/containers/DashRoutes.tsx
  src/containers/admin-dashBoard/TtlsModal.tsx
  src/pages/AdminTraineeDashboard.tsx
  tsconfig.json
  vercel.json
  webpack.config.js
Labels: Change Requested

#308 Update cover image
  src/components/ProfileCoverpage.tsx
  src/components/ProfileTabs.tsx
  src/components/Resume.tsx
  src/pages/AdminTraineeDashboard.tsx
  src/pages/tests/__snapshots__/userRegister.test.tsx.snap
Labels: Need Reviews

#326 Fix: new cohort visibility w/o refreshing the page
  src/containers/admin-dashBoard/CreateCohortModal.tsx
  src/pages/AdminTraineeDashboard.tsx
Labels: Need Reviews

#327 Admin shouldn't be able to rating
  src/components/ratings/ViewWeeklyRatings.tsx
Labels: Ready For Merge

#328 fix admin dashboard
  src/pages/AdminDashboard.tsx
Labels: Ready For Merge
