Repository atlp-rwanda/atlp-pulse-fn, pull requests merged in 2023-09, with the labels that each got.

#237 TTLs Page
  package-lock.json
  src/Mutations/User.tsx
  src/Mutations/teamMutation.tsx
  src/components/DataTable.tsx
  src/components/Sidebar.tsx
  src/components/chartGitHub.tsx
  src/containers/DashRoutes.tsx
  src/containers/admin-dashBoard/ManagerRoles.tsx
  src/containers/admin-dashBoard/Teams.tsx
  src/containers/admin-dashBoard/TtlsModal.tsx
  src/pages/Organization/AdminLogin.tsx
  src/pages/ttlTraineeDashboard.tsx
Labels: Ready For Merge

#290 fixing sockets
  beta_.conf
  src/components/TraineePerformance.tsx
  src/pages/ratings/CoordinatorRemarks.tsx
  src/pages/ratings/frame.tsx
Labels: Ready for review

#265 Rating Feature Implementation
  package-lock.json
  package.json
  public/locales/fr/translation.json
  public/locales/kn/translation.json
  src/App.tsx
  src/Mutations/Ratings.tsx
  src/Mutations/manageStudentMutations.tsx
  src/components/ratings/AddNewRatings.tsx
  src/components/ratings/Dropout.tsx
  src/components/ratings/ViewWeeklyRatings.tsx
  src/components/ratings/hooks/useAddNewRating.tsx
  src/components/ratings/hooks/useViewTraineeRatings.tsx
  src/containers/DashRoutes.tsx
  src/hook/useTraineesData.tsx
  src/pages/AdminTraineeDashboard.tsx
  src/pages/OrgRegister.tsx
  src/pages/ratings/ViewTraineeRatings.tsx
Labels: Ready for review

#289 fixing trainee and routes
  src/Mutations/manageStudentMutations.tsx
  src/components/Sidebar.tsx
  src/components/logoIcon.tsx
  src/containers/DashRoutes.tsx
  src/containers/admin-dashBoard/tests/Attendance.tsx
  src/pages/AdminTraineeDashboard.tsx
  src/pages/Organization/Message.tsx
  src/utils/CheckRoles.tsx
  src/utils/ProtectRoute.tsx
Labels: Ready For Merge

#294 fix attendance scores calculation
  src/pages/TraineeAttendance.tsx
Labels: Ready for review

#297 Fix-TTL-Page
  src/Mutations/manageStudentMutations.tsx
Labels: Ready For Merge

#252 Ft trainee dashboard
  package-lock.json
  src/Mutations/Ratings.tsx
  src/components/Sidebar.tsx
  src/components/TraineeDashboardChart.tsx
  src/components/TraineeTable.tsx
  src/components/TraineesChart.tsx
  src/components/TraineesHeader.tsx
  src/components/ViewComment.tsx
  src/index.css
  src/pages/Organization/AdminLogin.tsx
  src/pages/TraineeDashboard.tsx
  src/pages/TraineeRatingDashboard.tsx
  src/pages/tests/TraineeDashboard.test.tsx
  src/pages/tests/__snapshots__/TraineeDashboard.test.tsx.snap
  tsconfig.json
Labels: Need Reviews
