Repository atlp-rwanda/atlp-pulse-fn, pull requests merged in 2023-11, with the labels that each got.

#320 fix(bug):fix a super admin profile
  src/Mutations/Ratings.tsx
  src/components/ProfileTabs.tsx
Labels: Ready For Merge

#334 #315 Fix Input Validation Issue On Coordinator Dashboard
  public/locales/fr/translation.json
  public/locales/kn/translation.json
  src/pages/AdminTraineeDashboard.tsx
Labels: Need Reviews

#344 fix ticket design and responsiveness on dashboard
  package-lock.json
  package.json
  src/pages/AllTickets.tsx
  src/pages/Ticket.tsx
Labels: Need Reviews

#350 coordinator field in the content of view trainee
  src/Mutations/manageStudentMutations.tsx
  src/pages/AdminTraineeDashboard.tsx
Labels: waiting for bn

#343 Coordinator should update ratings
  package-lock.json
  src/components/ratings/ViewWeeklyRatings.tsx
  src/index.tsx
Labels: Need Reviews

#333 Fix-close modals after actions
  package-lock.json
  package.json
  src/containers/admin-dashBoard/CreateCohortModal.tsx
  src/pages/AdminTraineeDashboard.tsx
Labels: Change Requested

#348 trainee attendance feature FN
  package-lock.json
  package.json
  src/Mutations/Attendance.tsx
  src/components/TraineeAttendance.tsx
  src/components/teamDetails.tsx
  src/components/tests/TraineeAttendance.test.tsx
  src/components/tests/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  src/components/tests/__snapshots__/ProfileCoverpage.test.tsx.snap
  src/components/tests/__snapshots__/ProfileTabs.test.tsx.snap
  src/components/tests/__snapshots__/TraineeAttendance.test.tsx.snap
  src/containers/admin-dashBoard/tests/__snapshots__/Cohorts.test.tsx.snap
  src/pages/tests/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  src/pages/tests/__snapshots__/Admindash.test.tsx.snap
  src/pages/tests/__snapshots__/Profile.test.tsx.snap
  src/pages/tests/__snapshots__/userRegister.test.tsx.snap
Labels: Ready For Merge
