Repository atlp-rwanda/atlp-pulse-fn, pull requests merged in 2023-12, with the labels that each got.

#361 fixing update feedback
  src/Mutations/Ratings.tsx
  src/components/ratings/ViewWeeklyRatings.tsx
  src/containers/admin-dashBoard/Teams.tsx
  src/pages/UpdatedRatingDashboard.tsx
Labels: Need Reviews

#364 ft(admin-dashboard): Re-design trainee records
  src/pages/AdminTraineeDashboard.tsx
Labels: Need Reviews

#363 Admin get coordinators
  src/containers/admin-dashBoard/CoordinatorModal.tsx
Labels: Need Reviews, Ready For Merge

#359 fixing errors that appear in the console log
  src/ProtectedRoute.tsx
  src/components/Organizations.tsx
  src/index.tsx
  src/pages/AdminTraineeDashboard.tsx
  src/pages/Home.tsx
  src/pages/Organization/Orglogin.tsx
  src/utils/validateOrgToken.tsx
Labels: Ready For Merge
