Repository atlp-rwanda/atlp-pulse-fn, pull requests merged in 2024-09, with the labels that each got.

#457 Creating invitation page layout #438
  package-lock.json
  src/components/InvitationCard.tsx
  src/components/Sidebar.tsx
  src/containers/DashRoutes.tsx
  src/containers/admin-dashBoard/tests/session.test.tsx
  src/pages/invitation.tsx
  src/tests/about.test.tsx
  src/tests/invitation.test.tsx
  src/tests/invitationCard.test.tsx
Labels: Ready For Merge, Fighters

#446 #426 refactors and fixes user notifications feature
  package-lock.json
  src/Mutations/notificationMutation.tsx
  src/components/DashHeader.tsx
  src/components/Notification.tsx
  src/components/tests/Navbar.test.tsx
  src/index.css
  src/pages/AdminTraineeDashboard.tsx
  src/tests/Notification.test.tsx
  src/tests/__snapshots__/Notification.test.tsx.snap
Labels: Need Reviews, Steppers

#436 fix(trainee dashboard) remove performance details field
  src/components/Sidebar.tsx
  src/components/TraineePerformance.tsx
  src/containers/admin-dashBoard/tests/Sessions.test.tsx
  src/pages/tests/About.test.tsx
  src/tests/about.test.tsx
Labels: Ready For Merge, Nova

#459 #432 invite users using an excel file
  package-lock.json
  src/Mutations/invitationMutation.tsx
  src/components/invitationModal.tsx
  src/index.tsx
Labels: Need Reviews, Fighters

#467 #419 Admin Invitation table view PR
  .gitignore
  package.json
  src/components/InvitationTable.tsx
  src/pages/invitation.tsx
Labels: Need Reviews, Ready For Merge, Fighters

#437 Skeleton loader match to respective layout
  package-lock.json
  src/components/invitationModal.tsx
  src/containers/admin-dashBoard/tests/sessionTest.test.tsx
  src/index.tsx
  src/pages/invitation.tsx
  src/pages/tests/invitationModel.test.tsx
Labels: Ready For Merge, Nova

#458 fixing Trainee Filter
  package-lock.json
  src/components/DataTable.tsx
  src/pages/AdminTraineeDashboard.tsx
Labels: Ready For Merge, Nova

#463 #433 Ft Invitation Statistics Fe
  src/Mutations/invitationStats.tsx
  src/pages/invitation.tsx
Labels: Ready For Merge, Fighters

#468 #473 Improvement of invitation Page Layout
  src/components/InvitationCard.tsx
  src/pages/invitation.tsx
  tailwind.config.js
Labels: Ready For Merge, Fighters

#481 fixing Bugs on the trainees page on the admin dashboard
  src/pages/AdminTraineeDashboard.tsx
Labels: Ready For Merge, Nova

#485 #406 resolves admin profile issues
  package-lock.json
  src/Mutations/User.tsx
  src/Mutations/manageStudentMutations.tsx
  src/components/CountrySelector.tsx
  src/components/DashHeader.tsx
  src/components/Input.tsx
  src/components/ProfileCoverpage.tsx
  src/components/ProfileTabs.tsx
  src/components/tests/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  src/components/tests/__snapshots__/ButtonLoading.test.tsx.snap
  src/components/tests/__snapshots__/DashHeader.test.tsx.snap
  src/components/tests/__snapshots__/Footer.test.tsx.snap
  src/components/tests/__snapshots__/Header.test.tsx.snap
  src/components/tests/__snapshots__/ProfileCoverpage.test.tsx.snap
  src/components/tests/__snapshots__/ProfileDropdown.test.tsx.snap
  src/components/tests/__snapshots__/ProfileTabs.test.tsx.snap
  src/components/tests/__snapshots__/Resume.test.tsx.snap
  src/components/tests/__snapshots__/SideNavLink.test.tsx.snap
  src/components/tests/__snapshots__/Skeleton.test.tsx.snap
  src/components/tests/__snapshots__/TraineeAttendanceDetails.test.tsx.snap
  src/components/tests/__snapshots__/TraineeComments.test.tsx.snap
  src/containers/DashRoutes.tsx
  src/containers/Trainee/tests/__snapshots__/AttendanceDetails.test.tsx.snap
  src/containers/admin-dashBoard/tests/__snapshots__/Cohorts.test.tsx.snap
  src/containers/admin-dashBoard/tests/__snapshots__/Phase.test.tsx.snap
  src/containers/admin-dashBoard/tests/__snapshots__/Program.test.tsx.snap
  src/containers/tests/__snapshots__/MainRoutes.test.tsx.snap
  src/pages/AdminDashboard.tsx
  src/pages/Profile.tsx
  src/pages/ProfileEdit.tsx
  src/pages/tests/__snapshots__/About.test.tsx.snap
  src/pages/tests/__snapshots__/AdminLogin.test.tsx.snap
  src/pages/tests/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  src/pages/tests/__snapshots__/Admindash.test.tsx.snap
  src/pages/tests/__snapshots__/Error.test.tsx.snap
  src/pages/tests/__snapshots__/GradingSystem.test.tsx.snap
  src/pages/tests/__snapshots__/Home.test.tsx.snap
  src/pages/tests/__snapshots__/OrgLogin.test.tsx.snap
  src/pages/tests/__snapshots__/Pricing.test.tsx.snap
  src/pages/tests/__snapshots__/Profile.test.tsx.snap
  src/pages/tests/__snapshots__/SupAdDashboard.test.tsx.snap
  src/pages/tests/__snapshots__/TraineeAttendance.test.tsx.snap
  src/pages/tests/__snapshots__/TraineeRatingDashboard.test.tsx.snap
  src/pages/tests/__snapshots__/UpdateTraineeRating.test.tsx.snap
  src/pages/tests/__snapshots__/message.test.tsx.snap
  src/pages/tests/__snapshots__/userRegister.test.tsx.snap
  src/tests/__snapshots__/App.test.tsx.snap
  src/tests/__snapshots__/Notification.test.tsx.snap
  src/tests/__snapshots__/Pricing.test.tsx.snap
  src/tests/__snapshots__/Siderbar.test.tsx.snap
  tailwind.config.js
Labels: Need Reviews, Steppers

#488 #478 Filter Invitations statistics based on time range
  package-lock.json
  package.json
  src/Mutations/invitationStats.tsx
  src/Skeletons/InvitationCardSkeleton.tsx
  src/pages/invitation.tsx
Labels: Need Reviews, Ready For Merge, Fighters

#489 fix-trainee-profile-page
  public/locales/kn/translation.json
  src/Mutations/manageStudentMutations.tsx
  src/components/Buttons.tsx
  src/components/Notification.tsx
  src/components/ProfileTabs.tsx
  src/components/Resume.tsx
  src/components/tests/__snapshots__/Resume.test.tsx.snap
Labels: Need Reviews, Ready For Merge, Steppers

#492 fix(in adding ratings) Feedback field validation error
  package-lock.json
  package.json
  src/components/ratings/AddNewRatings.tsx
Labels: Ready For Merge, Nova

#494 #384 ttl rating trainees
  src/Mutations/User.tsx
  src/Mutations/invitationStats.tsx
  src/components/TraineePerformance.tsx
  src/components/ratings/ViewWeeklyRatings.tsx
  src/pages/invitation.tsx
  src/pages/ttlTraineeDashboard.tsx
Labels: Need Reviews, Steppers

#496 Fix allowing both ttl and coordinator rating trainee
  src/components/ratings/AddNewRatings.tsx
  src/components/ratings/ViewWeeklyRatings.tsx
  src/components/ratings/hooks/useViewTraineeRatings.tsx
  src/pages/AdminTraineeDashboard.tsx
  src/pages/ttlTraineeDashboard.tsx
Labels: Need Reviews, Steppers

#479 #476 Implememt delete invitations
  src/Mutations/invitationMutation.tsx
  src/components/InvitationTable.tsx
  src/components/invitationModal.tsx
  src/containers/DashRoutes.tsx
  src/pages/invitation.tsx
  src/pages/invitationModalComponet.tsx
Labels: Ready For Merge, Fighters

#493 #477 improving invitation filter
  src/components/InvitationTable.tsx
  src/containers/DashRoutes.tsx
  src/pages/invitation.tsx
  src/queries/invitation.queries.tsx
Labels: Need Reviews, Ready For Merge, Fighters

#490 Update invitation
  src/Mutations/invitationMutation.tsx
  src/Mutations/invitationStats.tsx
  src/components/InvitationTable.tsx
  src/components/invitationModal.tsx
  src/pages/invitation.tsx
  src/queries/invitation.queries.tsx
  src/tests/invitation.test.tsx
Labels: Need Reviews, Fighters

#491 #397 admin-update-teams
  src/components/ManagerCard.tsx
  src/components/teamDetails.tsx
  src/containers/admin-dashBoard/Teams.tsx
  src/containers/admin-dashBoard/UpdateTeamModal.tsx
Labels: enhancement, Ready For Merge, Nova

#518 #500 fix bug on table
  src/components/DataTable.tsx
  src/components/InvitationTable.tsx
  src/components/Sidebar.tsx
  src/pages/AdminTraineeDashboard.tsx
  src/pages/invitation.tsx
Labels: Ready For Merge, Fighters

#512 fix rating trainee
  src/components/ratings/ViewWeeklyRatings.tsx
  src/components/ratings/hooks/useAddNewRating.tsx
  src/components/tests/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  src/components/tests/__snapshots__/Header.test.tsx.snap
  src/components/tests/__snapshots__/ProfileTabs.test.tsx.snap
  src/components/tests/__snapshots__/Resume.test.tsx.snap
  src/components/tests/__snapshots__/TraineeAttendanceDetails.test.tsx.snap
  src/containers/Trainee/tests/__snapshots__/AttendanceDetails.test.tsx.snap
  src/containers/admin-dashBoard/tests/__snapshots__/Cohorts.test.tsx.snap
  src/containers/admin-dashBoard/tests/__snapshots__/Phase.test.tsx.snap
  src/containers/admin-dashBoard/tests/__snapshots__/Program.test.tsx.snap
  src/containers/tests/__snapshots__/MainRoutes.test.tsx.snap
  src/pages/AdminTraineeDashboard.tsx
  src/pages/tests/__snapshots__/AdminLogin.test.tsx.snap
  src/pages/tests/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  src/pages/tests/__snapshots__/Admindash.test.tsx.snap
  src/pages/tests/__snapshots__/Error.test.tsx.snap
  src/pages/tests/__snapshots__/GradingSystem.test.tsx.snap
  src/pages/tests/__snapshots__/Home.test.tsx.snap
  src/pages/tests/__snapshots__/OrgLogin.test.tsx.snap
  src/pages/tests/__snapshots__/Profile.test.tsx.snap
  src/pages/tests/__snapshots__/UpdateTraineeRating.test.tsx.snap
  src/pages/tests/__snapshots__/userRegister.test.tsx.snap
  src/pages/ttlTraineeDashboard.tsx
  src/tests/__snapshots__/App.test.tsx.snap
  src/tests/__snapshots__/Notification.test.tsx.snap
  src/tests/__snapshots__/Siderbar.test.tsx.snap
Labels: Need Reviews, Ready For Merge, Steppers
