Repository atlp-rwanda/atlp-pulse-fn, pull requests merged in 2024-11, with the labels that each got.

#617 average ratings
  src/components/InvitationTable.tsx
  src/components/NotFoundPage.tsx
  src/containers/admin-dashBoard/TeamTraineeModal.tsx
  src/queries/manageStudent.queries.tsx
Labels: Ready For Merge, Nova

#603 #513 refactoring attendance feature on trainee side
  package-lock.json
  package.json
  src/Mutations/Attendance.tsx
  src/components/AttendanceSymbols.tsx
  src/components/EditAttendenceButton.tsx
  src/components/ModalAttendance.tsx
  src/components/Sidebar.tsx
  src/components/TraineeAttendance.tsx
  src/pages/Attendance.tsx
  src/pages/Organization/AdminLogin.tsx
  src/pages/TraineeAttendance.tsx
  src/pages/TraineeAttendanceTracker.tsx
  src/queries/attendance.queries.tsx
  src/queries/team.queries.tsx
  src/utils/getDateForDays.ts
  tests/components/EditAttendenceButton.test.tsx
  tests/components/ModalAttendance.test.tsx
  tests/components/TraineeAttendance.test.tsx
  tests/components/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  tests/components/__snapshots__/EditAttendenceButton.test.tsx.snap
  tests/components/__snapshots__/SideNavLink.test.tsx.snap
  tests/containers/__snapshots__/MainRoutes.test.tsx.snap
  tests/other-tests/__snapshots__/App.test.tsx.snap
  tests/other-tests/__snapshots__/Siderbar.test.tsx.snap
  tests/pages/TraineeAttendance.test.tsx
  tests/pages/TraineeAttendanceTracker.test.tsx
  tests/pages/__snapshots__/About.test.tsx.snap
  tests/pages/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  tests/pages/__snapshots__/TraineeAttendance.test.tsx.snap
  tests/pages/__snapshots__/TraineeAttendanceTracker.test.tsx.snap
  tests/pages/__snapshots__/userRegister.test.tsx.snap
  tests/utils/getDateForDays.test.tsx
  tsconfig.json
Labels: Need Reviews, Steppers

#618 #422-fx-Enable admin to view all programs with user breakdown per program
  src/components/DataPagination.tsx
  src/components/ProgramUsersModal.tsx
  src/containers/admin-dashBoard/Programs.tsx
  tests/components/Calendar.test.tsx
Labels: Need Reviews, Nova

#608 #506 implement coordinator dashboard
  src/components/DataTable.tsx
  src/pages/CoordinatorDashboard.tsx
  src/pages/Dashboard.tsx
  src/pages/coordinatorTraineDashboard.tsx
  src/queries/ratings.queries.tsx
  tests/components/Calendar.test.tsx
Labels: Need Reviews, Nova

#616 fix(#318) add request approval link to org email
  src/ProtectedRoute.tsx
  src/components/Organizations.tsx
  src/pages/Organization/AdminLogin.tsx
Labels: Need Reviews, Fighters

#625 #621 Ft implements a super admin dashboard
  package-lock.json
  package.json
  src/assets/dash-event-icon.svg
  src/assets/multiple-users.svg
  src/assets/no-event.png
  src/components/Calendar.tsx
  src/components/OrgStatusSymbol.tsx
  src/components/Organizations.tsx
  src/components/icons/MultipleLogins.tsx
  src/containers/DashRoutes.tsx
  src/pages/Dashboard.tsx
  src/pages/Organization/AdminLogin.tsx
  src/pages/SupAdDashboard.tsx
  src/pages/SuperAdminDashboard.tsx
  src/queries/organization.queries.tsx
  tailwind.config.js
  tests/components/Calendar.test.tsx
  tests/components/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  tests/containers/admin-dashboard/__snapshots__/Cohorts.test.tsx.snap
  tests/pages/SupAdDashboard.test.tsx
  tests/pages/SuperAdminDashboard.test.tsx
  tests/pages/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  tests/pages/__snapshots__/Admindash.test.tsx.snap
  tests/pages/__snapshots__/GradingSystem.test.tsx.snap
  tests/pages/__snapshots__/SupAdDashboard.test.tsx.snap
  tests/pages/__snapshots__/SuperAdminDashboard.test.tsx.snap
  tests/pages/__snapshots__/TraineeRatingDashboard.test.tsx.snap
  tests/pages/__snapshots__/UpdateTraineeRating.test.tsx.snap
  tests/pages/__snapshots__/userRegister.test.tsx.snap
Labels: Ready For Merge, Steppers

#624 adding community page
  src/components/Buttons.tsx
  src/components/CommunityQuestions.tsx
  src/components/Footer.tsx
  src/components/ProgramUsersModal.tsx
  src/containers/Routes.tsx
  src/pages/Community.tsx
  src/queries/questions.query.tsx
Labels: Need Reviews, Steppers

#615 two factor authentication on fn
  src/containers/DashRoutes.tsx
  src/containers/Routes.tsx
  src/pages/LoginWith2fa.tsx
  src/pages/Organization/2faMutation.tsx
  src/pages/Organization/AdminLogin.tsx
  src/pages/Organization/LoginMutation.tsx
  src/pages/Settings.tsx
  tests/pages/LoginWith2fa.test.tsx
Labels: enhancement, Ready For Merge, Nova

#589 fixing new tickets button color and trimming message
  src/pages/Tickets.tsx
Labels: Need Reviews

#628 fixing community page theme
  src/ProtectedRoute.tsx
  src/components/CommunityQuestions.tsx
  src/queries/questions.query.tsx
Labels: Need Reviews, Steppers

#602 #328 fx-adding input validations
  src/pages/gradeSystem/addNew.tsx
  src/pages/gradeSystem/gradeItem.tsx
  tests/components/MobileDropdown.test.tsx
  tests/components/RedirectHandler.test.tsx
  tests/components/addNew.test.tsx
Labels: Need Reviews, Nova

#632 Fx sidebar scroll
  src/components/DashHeader.tsx
  src/components/Sidebar.tsx
  src/containers/DashRoutes.tsx
  src/hook/menuProvider.tsx
  src/index.css
  tests/components/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  tests/components/__snapshots__/DashHeader.test.tsx.snap
  tests/components/__snapshots__/Footer.test.tsx.snap
  tests/components/__snapshots__/SideNavLink.test.tsx.snap
  tests/containers/__snapshots__/MainRoutes.test.tsx.snap
  tests/other-tests/__snapshots__/App.test.tsx.snap
  tests/other-tests/__snapshots__/Siderbar.test.tsx.snap
  tests/pages/TraineeAttendance.test.tsx
  tests/pages/__snapshots__/AdminLogin.test.tsx.snap
  tests/pages/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  tests/pages/__snapshots__/Home.test.tsx.snap
  tests/pages/__snapshots__/Settings.test.tsx.snap
  tests/pages/__snapshots__/SuperAdminDashboard.test.tsx.snap
  tests/pages/__snapshots__/userRegister.test.tsx.snap
Labels: Ready For Merge, Steppers

#528 Fix: Update Trainee Dashboard
  package-lock.json
  package.json
  src/components/DashHeader.tsx
  src/components/DataTable.tsx
  src/components/TraineeDashboardChart.tsx
  src/components/TraineeHeader.tsx
  src/components/TraineePerformance.tsx
  src/components/TraineesHeader.tsx
  src/components/ViewComment.tsx
  src/pages/TraineeDashboard.tsx
  src/queries/ratings.queries.tsx
  tests/components/__snapshots__/DashHeader.test.tsx.snap
  tests/pages/__snapshots__/GradingSystem.test.tsx.snap
  tests/pages/__snapshots__/TraineeRatingDashboard.test.tsx.snap
  tests/pages/__snapshots__/UpdateTraineeRating.test.tsx.snap
Labels: Ready For Merge, Steppers

#629 Fix coordinators table
  src/Mutations/User.tsx
  src/components/DataTable.tsx
  src/components/DropOrUndropUser.tsx
  src/components/ViewComment.tsx
  src/containers/admin-dashBoard/CoordinatorModal.tsx
  src/containers/admin-dashBoard/TtlsModal.tsx
  src/pages/LoginWith2fa.tsx
  src/pages/Organization/AdminLogin.tsx
  src/pages/TraineeDashboard.tsx
  src/queries/manageStudent.queries.tsx
  tests/pages/LoginWith2fa.test.tsx
Labels: Need Reviews, Steppers

#638 fixing login with 2fa
  src/pages/LoginWith2fa.tsx
  src/pages/Organization/AdminLogin.tsx
  src/pages/Organization/LoginMutation.tsx
  tests/pages/LoginWith2fa.test.tsx
Labels: bug, Need Reviews, Nova

#597 #417 Add Bulk Rating
  package-lock.json
  package.json
  src/Mutations/Ratings.tsx
  src/Mutations/cohortMutations.tsx
  src/Mutations/teamMutation.tsx
  src/components/BulkRatingModal.tsx
  src/pages/AdminTraineeDashboard.tsx
  src/pages/ttlTraineeDashboard.tsx
  tests/components/BulkRatingModal.test.tsx
  tests/components/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  tests/pages/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  tests/pages/__snapshots__/GradingSystem.test.tsx.snap
  tests/pages/__snapshots__/TraineeRatingDashboard.test.tsx.snap
  tests/pages/__snapshots__/UpdateTraineeRating.test.tsx.snap
  tests/pages/__snapshots__/userRegister.test.tsx.snap
Labels: Ready For Merge, Nova

#637 adding ttl and trainee attendance loading
  jest.config.js
  src/Skeletons/Team.skeleton.tsx
  src/Skeletons/attendance.skeleton.tsx
  src/components/BulkRatingModal.tsx
  src/components/CoordinatorCard.tsx
  src/components/TraineeHeader.tsx
  src/pages/LoginWith2fa.tsx
  src/pages/TraineeAttendanceTracker.tsx
  src/pages/TraineeDashboard.tsx
  tests/components/__snapshots__/CoordinatorCard.test.tsx.snap
  tests/pages/TraineeAttendanceTracker.test.tsx
  tests/pages/__snapshots__/GradingSystem.test.tsx.snap
  tests/pages/__snapshots__/TraineeAttendanceTracker.test.tsx.snap
  tests/pages/__snapshots__/TraineeRatingDashboard.test.tsx.snap
  tests/pages/__snapshots__/UpdateTraineeRating.test.tsx.snap
Labels: Need Reviews, Steppers

#639 trainee-stats-ttl
  src/pages/ttlTraineeDashboard.tsx
  src/queries/user.queries.tsx
Labels: Ready For Merge, Steppers
