Repository atlp-rwanda/atlp-pulse-fn, pull requests merged in 2024-10, with the labels that each got.

#511 #502 web-perfomance load time : Migration from CRA to Vite
  .eslintrc
  index.html
  jest.config.js
  package-lock.json
  package.json
  postcss.config.js
  src/components/InvitationTable.tsx
  src/pages/GradingSystem.tsx
  target/npmlist.json
  vite.config.ts
Labels: Need Reviews, Nova

#515 fixing fetching invitations for specific organization
  src/pages/invitation.tsx
  src/queries/invitation.queries.tsx
Labels: Need Reviews, Fighters

#527 #521 Separating mutations and components
  src/Mutations/OrganisationMutations.tsx
  src/Mutations/cohortMutations.tsx
  src/Mutations/coverMutations.tsx
  src/Mutations/phaseMutations.tsx
  src/Mutations/profileMutation.tsx
  src/Mutations/programMutations.tsx
  src/Mutations/resumeMutation.tsx
  src/Mutations/teamMutation.tsx
  src/components/CreateOrganizationModal.tsx
  src/components/Organizations.tsx
  src/components/ProfileCoverpage.tsx
  src/components/Resume.tsx
  src/containers/admin-dashBoard/CreateCohortModal.tsx
  src/containers/admin-dashBoard/CreatePhaseModal.tsx
  src/containers/admin-dashBoard/CreateProgramModal.tsx
  src/containers/admin-dashBoard/CreateTeamModal.tsx
  src/containers/admin-dashBoard/DeleteCohortModal.tsx
  src/containers/admin-dashBoard/DeletePhaseModal.tsx
  src/containers/admin-dashBoard/DeleteProgramModal.tsx
  src/containers/admin-dashBoard/DeleteTeamModal.tsx
  src/containers/admin-dashBoard/Programs.tsx
  src/pages/ProfileEdit.tsx
Labels: Need Reviews, Fighters

#529 Removing commented-out sections that are not being used
  package-lock.json
  src/pages/AdminDashboard.tsx
  src/pages/AdminTraineeDashboard.tsx
Labels: Fighters

#530 admin should be able to resend pending invitations
  src/Mutations/invitationMutation.tsx
  src/pages/invitation.tsx
Labels: Fighters

#480 advancing calender functionality
  jest.config.js
  package-lock.json
  package.json
  src/Mutations/User.tsx
  src/Mutations/event.tsx
  src/Mutations/manageStudentMutations.tsx
  src/components/Calendar.tsx
  src/components/CalendarConfirmation.tsx
  src/components/CoordinatorCard.tsx
  src/components/EventGuestList.tsx
  src/containers/Routes.tsx
  tests/components/Calendar.test.tsx
  tests/components/CalendarConfirmation.test.tsx
  tests/components/EventGuestList.test.tsx
  tests/components/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  tests/containers/admin-dashboard/__snapshots__/Cohorts.test.tsx.snap
  tests/containers/admin-dashboard/__snapshots__/Program.test.tsx.snap
  tests/other-tests/AdminDashboard.test.tsx
  tests/pages/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  tests/pages/__snapshots__/Admindash.test.tsx.snap
  tests/pages/__snapshots__/Settings.test.tsx.snap
  tests/pages/__snapshots__/userRegister.test.tsx.snap
Labels: Ready For Merge, Nova

#532 adding undrop trainee feature
  src/Mutations/manageStudentMutations.tsx
  src/pages/AdminTraineeDashboard.tsx
  src/pages/Organization/AdminLogin.tsx
Labels: Need Reviews, Steppers

#535 resolve blank space issue
  src/containers/DashRoutes.tsx
Labels: bug, Ready For Merge, Nova

#548 #537 Improving table loading state PR
  src/Skeletons/SkeletonTable.tsx
  src/components/InvitationTable.tsx
  src/pages/invitation.tsx
  tsconfig.json
Labels: enhancement, Need Reviews, Fighters

#569 #555 Implement fix on action Modal on tables
  src/components/DataTable.tsx
  src/components/InvitationTable.tsx
  src/pages/AdminTraineeDashboard.tsx
  src/pages/invitation.tsx
Labels: Need Reviews, Fighters

#567 #557 Update Invite Form for email and role validation
  src/components/invitationModal.tsx
Labels: Need Reviews, Fighters

#550 Fixes recording attendance bug
  package-lock.json
  package.json
  src/Mutations/Attendance.tsx
  src/components/ModalAttendance.tsx
  src/pages/TraineeAttendanceTracker.tsx
  src/queries/team.queries.tsx
  tests/components/ModalAttendance.test.tsx
  tests/components/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  tests/components/__snapshots__/Footer.test.tsx.snap
  tests/containers/__snapshots__/MainRoutes.test.tsx.snap
  tests/other-tests/__snapshots__/App.test.tsx.snap
  tests/other-tests/__snapshots__/Siderbar.test.tsx.snap
  tests/pages/TraineeAttendanceTracker.test.tsx
  tests/pages/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  tests/pages/__snapshots__/Home.test.tsx.snap
  tests/pages/__snapshots__/TraineeAttendanceTracker.test.tsx.snap
  tests/pages/__snapshots__/userRegister.test.tsx.snap
Labels: Need Reviews, Steppers

#568 Fix updated ratings page
  src/pages/UpdatedRatingDashboard.tsx
  tests/pages/__snapshots__/UpdateTraineeRating.test.tsx.snap
Labels: Ready For Merge, Nova

#564 #556 Table Pagination Responsiveness
  src/components/DataPagination.tsx
Labels: Need Reviews, Fighters

#570 Fix suspend users
  src/components/ratings/Dropout.tsx
  src/containers/admin-dashBoard/GetRolesQuery.tsx
  src/containers/admin-dashBoard/ManagerRoles.tsx
  src/index.tsx
  src/pages/Organization/AdminLogin.tsx
Labels: Need Reviews, Steppers

#584 #580 Update dark background color on desktop to match with on mobile design
  src/components/InvitationCard.tsx
Labels: Need Reviews, Fighters

#585 next redirect
  src/utils/ProtectRoute.tsx
Labels: bug, Need Reviews, Nova

#573 #413 fix Trainee edit profile
  package-lock.json
  package.json
  src/components/Input.tsx
  src/constants/formFields.ts
  src/index.css
  src/pages/ProfileEdit.tsx
  tests/pages/Profile.test.tsx
Labels: Ready For Merge, Nova

#586 #582 Re-designing seach bar, filter and sorting
  src/pages/AdminTraineeDashboard.tsx
  src/pages/invitation.tsx
Labels: Need Reviews, Fighters

#572 Fx-Fonts-harmonization
  src/components/loaders/loader1/style.module.css
  src/components/loaders/loader2/style.module.css
  src/index.css
  src/pages/Organization/orgName.css
  src/pages/gradeSystem/style.module.css
  src/pages/ratings/style.module.css
  src/style.css
  tailwind.config.js
Labels: Ready For Merge, Steppers

#590 #581 sort invitations
  src/pages/invitation.tsx
  src/queries/invitation.queries.tsx
Labels: Need Reviews, Fighters

#591 #578 Improving search invitation to listern to typing event
  src/components/InvitationTable.tsx
  src/pages/invitation.tsx
  src/queries/invitation.queries.tsx
Labels: Need Reviews, Ready For Merge, Fighters

#576 404 fix: Login Activities
  src/components/LoginActivitiesTable.tsx
  src/components/TraineePerformance.tsx
Labels: Need Reviews, Nova

#593 Adding a not found page
  src/App.tsx
  src/components/NotFoundPage.tsx
  src/containers/DashRoutes.tsx
  src/containers/Routes.tsx
Labels: Need Reviews, Nova

#553 #599 Improve invitation table pagination
  package-lock.json
  package.json
  src/components/InvitationDataPagination.tsx
  src/components/InvitationTable.tsx
  src/hook/UsePagination.tsx
  src/pages/invitation.tsx
  src/queries/invitation.queries.tsx
Labels: Need Reviews, Fighters

#598 #595 Improve the dark mode skeleton to match the dark design
  src/Skeletons/InvitationCardSkeleton.tsx
  src/Skeletons/SkeletonTable.tsx
Labels: Need Reviews, Fighters

#600 #404 add skeleton loader on login activities table
  src/Skeletons/loginActivities.skeleton.tsx
  src/components/LoginActivitiesTable.tsx
  tests/components/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  tests/components/__snapshots__/DashHeader.test.tsx.snap
  tests/components/__snapshots__/Header.test.tsx.snap
  tests/components/loginActivities.test.tsx
  tests/containers/admin-dashboard/__snapshots__/Cohorts.test.tsx.snap
  tests/pages/__snapshots__/AdminTraineeDashboard.test.tsx.snap
  tests/pages/__snapshots__/Admindash.test.tsx.snap
  tests/pages/__snapshots__/GradingSystem.test.tsx.snap
  tests/pages/__snapshots__/Home.test.tsx.snap
  tests/pages/__snapshots__/Profile.test.tsx.snap
  tests/pages/__snapshots__/TraineeRatingDashboard.test.tsx.snap
  tests/pages/__snapshots__/UpdateTraineeRating.test.tsx.snap
  tests/pages/__snapshots__/userRegister.test.tsx.snap
Labels: Need Reviews, Nova

#594 #225 fx-Remove ratings legacy feature
  src/Mutations/Ratings.tsx
  src/Mutations/replyMutation.tsx
  src/components/TraineePerformance.tsx
  src/components/TraineePerformanceDetails.tsx
  src/components/ratings/ViewWeeklyRatings.tsx
  src/components/ratings/hooks/useAddNewRating.tsx
  src/pages/AdminRatings.tsx
  src/pages/TraineeDashboard.tsx
  src/pages/TraineeRatingDashboard.tsx
  src/pages/UpdatedRatingDashboard.tsx
  src/pages/ratings/addRatings.tsx
  src/pages/ratings/frame.tsx
  src/queries/ratings.queries.tsx
  src/queries/reply.queries.tsx
  tests/pages/ratings/frame.test.tsx
Labels: Need Reviews, Nova

#607 #391 Enable Consistent Edit For All Cohorts
  src/containers/admin-dashBoard/CohortTraineeModal.tsx
  src/containers/admin-dashBoard/UpdateCohortModal.tsx
Labels: Fighters

#611 #605 Fix table responsiveness
  src/components/DataTable.tsx
  src/pages/invitation.tsx
Labels: Need Reviews, Ready For Merge, Fighters

#613 #606 Harmonize action button theme across tables in TTL's portal
  src/pages/ttlTraineeDashboard.tsx
Labels: Need Reviews, Fighters

#614 #394: Resolve Trainee Detail View Errors
  src/pages/AdminTraineeDashboard.tsx
Labels: Need Reviews, Fighters
